name: shortcut
description: "Short-form addiction checker"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.2.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  go_router: ^13.2.0
  dio: ^5.4.1
  equatable: ^2.0.5
  app_usage: ^3.0.1
  permission_handler: ^11.3.0
  flutter_local_notifications: ^16.3.2
  flutter_riverpod: ^2.4.10
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  hooks_riverpod: ^2.4.10
  syncfusion_flutter_gauges: 24.1.45
  syncfusion_flutter_charts: 24.1.45
  syncfusion_flutter_core: 24.1.45
  flutter_animate: ^4.5.0
  shared_preferences: ^2.2.2
  build_runner: ^2.4.8
  device_preview: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  custom_lint: ^0.6.2
  riverpod_lint: ^2.3.9
  riverpod_generator: ^2.3.11
  freezed: ^2.4.7
  json_serializable: ^6.7.1
  mocktail: ^1.0.3
  flutter_lints: ^3.0.1

flutter:

  uses-material-design: true

  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
